name: viet_wallet
description: Flutter project final in KMA.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1
  flutter_app_badger: ^1.5.0
  equatable: ^2.0.5
  connectivity_plus: ^3.0.3
  flutter_secure_storage: ^8.0.0
  intl: ^0.17.0
  flutter_otp_text_field: ^1.1.1
  syncfusion_flutter_charts: ^20.4.42
  mat_month_picker_dialog: ^1.1.1

  flutter_datetime_picker: ^1.5.1
  flutter_localization: ^0.1.7
  currency_picker: ^2.0.13
  flutter_switch: ^0.3.2
  permission_handler: ^10.2.0
  path_provider: ^2.0.15
  local_auth_android: ^1.0.19
  local_auth: ^2.1.5
  dio: ^5.0.1
  dio_cookie_manager: ^2.1.1
  badges: ^3.0.2
  flutter_bloc: ^8.1.2
  open_file: ^3.3.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_messaging: ^14.6.1
  firebase_core: ^2.13.0
  firebase_storage: ^11.0.11
  firebase_in_app_messaging: ^0.7.3+1
  flutter_local_notifications: ^13.0.0

  image_picker: ^0.8.7
  cached_network_image: ^3.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
